version: "3"
services:
  app_fiber:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: app_fiber
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /app
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dev
