version: "3"
services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.46
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "6831:6831/udp"
      - "5775:5775/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"
      - "14269:14269"
      - "14250:14250"
      - "9411:9411"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "16685:16685"
    networks:
      - dev

  app_fiber:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: app_fiber
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /app
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dev

networks:
  dev :
    external: true